BugTracker/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BugTracker.Models;
using BugTracker.HelperExtensions;
using Microsoft.AspNet.Identity;
using System.Collections;
using System.Data.Entity;

namespace BugTracker.Controllers
{
    [RequireHttps]
    public class AdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Users
        [Authorize(Roles = "Project Manager, Administrator")]
        public ActionResult Users()
        {
            var users = db.Users.Include(u=>u.Projects).ToList();
            return View(users);
        }

        //GET: Admin/Users
        [Authorize(Roles = "Project Manager, Administrator")]
        public PartialViewResult _UserInfo(string id)
        {
            var model = new UserInfoViewModel();
            model.User = db.Users.Find(id);
            model.AssignedProjects = db.Projects.Where(p=>p.ProjectManagerId == id).ToList();
            model.AssignedTickets = id.ListUserTickets();
            model.SelectedRoles = id.ListUserRoles().ToList();
            model.AllRoles = new MultiSelectList(db.Roles, "Name", "Name", model.SelectedRoles);

            return PartialView(model);
        }

        //POST: Admin/Users/AddRemoveRole/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult AddRemoveRole(string userId, List<string> SelectedRoles)
        {
            var user = db.Users.Find(userId);

            if (ModelState.IsValid)
            {
                var roles = db.Roles.ToList();
                foreach (var role in roles.Select(r => r.Name))
                {
                    if (SelectedRoles.Contains(role))
                        user.Id.AddUserToRole(role);
                    else
                        if (user.Id.UserIsInRole(role))
                        user.Id.RemoveUserFromRole(role);
                    //UserManager handles validation for us, ex: user is already in role when add is attempted. Fails silently.
                }

                //notify user of role change
                //var es = new EmailService();
                //var user = db.Users.Find(model.User.Id);
                //var msg = user.CreateUserRolesModifiedMessage();
                //es.Send(msg);

                ViewBag.SuccessMessage = "User roles have been successfully updated.";
                return RedirectToAction("Users");
            }

            ViewBag.ErrorMessage = "Something went wrong. Please try again, or contact tech support.";
            //return RedirectToAction("Users");
            return RedirectToAction("Users");
        }

        //GET:Admin/Notifications
        public ActionResult Notifications()
        {
            var notifications = db.Notifications.ToList();
            var model = new List<NotificationsViewModel>();
            foreach (var notif in notifications)
            {
                var project = db.Projects.Find(notif.ProjectId);
                var ticket = db.Tickets.Find(notif.TicketId);
                var type = db.NotificationTypes.Find(notif.TypeId);
                var message = notif.Message.Replace("<br/>", " | "); ;

                model.Add(new NotificationsViewModel
                {
                    ProjectName = project != null ? project.Name : null,
                    TicketName = ticket != null ? ticket.Name : null,
                    Type = type.Name,
                    Recipients = notif.Recipients,
                    SendDate = notif.SendDate.FormatDateTimeOffset(),
                    Message = message
                });
            }

            return View(model);
        }

        ////GET: Admin/Roles/_AddRemoveUsers/roleName
        //[Authorize(Roles = "Administrator")]
        //public PartialViewResult _AddRemoveUsers(string roleName)
        //{
        //    var users = new List<string>();
        //    foreach (var user in db.Users)
        //        users.Add(user.FullName);

        //    var model = new AddRemoveUsersViewModel();
        //    model.RoleName = roleName;
        //    model.Users = new MultiSelectList(db.Users, "Id", "FullName", users);

        //    return PartialView(model);
        //}

        ////GET: Admin/Roles
        //[Authorize(Roles = "Administrator")]
        //public ActionResult Roles()
        //{
        //    var developers = db.Roles.FirstOrDefault(r => r.Name == "Developer").Name.UsersInRole().AsEnumerable();
        //    var administrators = db.Roles.FirstOrDefault(r => r.Name == "Administrator").Name.UsersInRole().AsEnumerable();
        //    var projectManagers = db.Roles.FirstOrDefault(r => r.Name == "Project Manager").Name.UsersInRole().AsEnumerable();
        //    var submitters = db.Roles.FirstOrDefault(r => r.Name == "Submitter").Name.UsersInRole().AsEnumerable();

        //    var model = new RolesIndexViewModel()
        //    {
        //        Submitters = submitters,
        //        Developers = developers,
        //        ProjectManagers = projectManagers,
        //        Administrators = administrators
        //    };

        //    return View(model);
        //}
    }
}

BugTracker/Controllers/ProjectsController.cs
using BugTracker.HelperExtensions;
using BugTracker.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    [RequireHttps]
    [Authorize]
    public class ProjectsController : Controller
    {
        private static ApplicationDbContext db = new ApplicationDbContext();
        private Dictionary<int, NotificationType> types = new Dictionary<int, NotificationType>()
        {
            { 1, new NotificationType {Id=9, Name="Ticket Submitted" } },
            { 2, new NotificationType {Id=1, Name="Ticket Assigned" } },
            { 3, new NotificationType {Id=4, Name="Ticket Modified" } },
            { 4, new NotificationType {Id=5, Name="Ticket Reassigned" } },
            { 5, new NotificationType {Id=2, Name="Ticket Resolved" } },
            { 6, new NotificationType {Id=3, Name="Reminder:Update Tickets" } },
            { 7, new NotificationType {Id=6, Name="Project Assigned" } },
            { 8, new NotificationType {Id=7, Name="Project Reassigned" } },
            { 9, new NotificationType {Id=8, Name="New Project Manager" } },
            {10, new NotificationType {Id=9, Name="Project Deadline Changed" } }
        };

        // GET: Projects/Index
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            List<Project> projects;

            if (User.IsInRole("Administrator"))
                projects = db.Projects.Where(p => p.IsResolved != true).OrderByDescending(p => p.Deadline).ToList();
            else
                projects = userId.ListUserProjects().ToList();

            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(projects);
        }

        // GET: Projects/Details/5
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Details(int? id)
        {
            Project project = db.Projects.Include(p=>p.Tickets).FirstOrDefault(p=>p.Id==id);

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (project == null)
                return HttpNotFound();

            return View(project);
        }

        //GET: Projects/Create
        public ActionResult Create()
        {
            var managers = db.Roles.FirstOrDefault(r => r.Name == "Project Manager").Name.UsersInRole().AsEnumerable();
            var developers = db.Roles.FirstOrDefault(r => r.Name == "Developer").Name.UsersInRole().AsEnumerable();
            var submitters = db.Roles.FirstOrDefault(r => r.Name == "Submitter").Name.UsersInRole().AsEnumerable();

            var model = new CreateEditProjectViewModel()
            {
                Project = new Project(),
                ProjectManagers = new SelectList(managers, "Id", "FullName"),
                Developers = new MultiSelectList(developers, "FullName", "FullName"),
                Submitters = new MultiSelectList(submitters, "FullName", "FullName")
            };

            return View(model);
        }

        // POST: Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create(Project project, List<string> SelectedDevelopers, List<string> SelectedSubmitters)
        {
            var userId = User.Identity.GetUserId();
            var manager = db.Users.Find(project.ProjectManagerId);
            var defaultManager = db.Users.Find(userId);

            if (ModelState.IsValid)
            {
                project.Created = DateTimeOffset.Now;
                db.Projects.Add(project);

                if (manager == null && userId.UserIsInRole("Project Manager"))
                {
                    project.ProjectManagerId = userId;
                    project.Users.Add(defaultManager);
                }
                else if (manager != null)
                    project.Users.Add(manager);

                //notify project manager
                var es = new EmailService();
                var msg = project.CreateAssignedToProjectMessage(manager != null ? manager : defaultManager);
                es.Send(msg);

                //log notification
                var notif = project.Id.CreateProjectNotification(types[7], new List<ApplicationUser> { manager != null ? manager : defaultManager }, msg.Body);
                db.Notifications.Add(notif);

                //add users
                if (project.Users != null)
                {
                    foreach (var user in db.Users)
                    {
                        if (SelectedDevelopers.Contains(user.FullName))
                            project.Users.Add(user);
                        if (SelectedSubmitters.Contains(user.FullName) && !project.Users.Any(u => u.FullName == user.FullName))
                            project.Users.Add(user);
                    }
                }

                db.SaveChanges();

                TempData["SuccessMessage"] = "Project " + project.Name + " created.";
                return RedirectToAction("Index");
            }

            TempData["ErrorMessage"] = "Something went wrong. Please try again or submit a ticket.";
            return RedirectToAction("Index");
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Edit(int id)
        {
            Project project = db.Projects.Find(id);

            var projectUsers = project.Users.ToList();
            var managers = db.Roles.FirstOrDefault(r => r.Name == "Project Manager").Name.UsersInRole();
            var developers = db.Roles.FirstOrDefault(r => r.Name == "Developer").Name.UsersInRole();
            var submitters = db.Roles.FirstOrDefault(r => r.Name == "Submitter").Name.UsersInRole();
            var selectedManager = db.Users.Find(project.ProjectManagerId);
            var selectedDevelopers = new List<string>();
            var selectedSubmitters = new List<string>();

            foreach (var user in projectUsers)
            {
                if (user.Id.UserIsInRole("Developer"))
                    selectedDevelopers.Add(user.FullName);
                if (user.Id.UserIsInRole("Submitter"))
                    selectedSubmitters.Add(user.FullName);
            }

            var model = new CreateEditProjectViewModel()
            {
                Project = project,
                ProjectManagers = new SelectList(managers, "Id", "FullName", selectedManager),
                Developers = new MultiSelectList(developers, "FullName", "FullName", selectedDevelopers),
                Submitters = new MultiSelectList(submitters, "FullName", "FullName", selectedSubmitters)
            };

            return View(model);
        }

        // POST: Projects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Edit([Bind(Include = "Id,ProjectManagerId,Name,Deadline,Description,Version")]Project project, List<string> SelectedDevelopers, List<string> SelectedSubmitters)
        {
            var original = db.Projects.AsNoTracking().FirstOrDefault(p => p.Id == project.Id);
            var origManager = db.Users.Find(original.ProjectManagerId);
            var manager = db.Users.Find(project.ProjectManagerId);
            var userId = User.Identity.GetUserId();
            var es = new EmailService();

            var proj = db.Projects.Find(project.Id);
            proj.Name = project.Name;
            proj.ProjectManagerId = project.ProjectManagerId;
            proj.Version = project.Version;
            proj.Deadline = project.Deadline;
            proj.Description = project.Description;
            proj.LastModified = DateTimeOffset.Now;

            if (ModelState.IsValid)
            {
                //reassign current users
                proj.Users.Clear();
                foreach (var user in db.Users)
                {
                    if (SelectedDevelopers.Contains(user.FullName))
                        proj.Users.Add(user);
                    if (SelectedSubmitters.Contains(user.FullName) && !proj.Users.Any(u => u.FullName == user.FullName))
                        proj.Users.Add(user);
                }

                var developers = "Developer".UsersInRole();
                var projectDevs = new List<ApplicationUser>();
                foreach (var dev in developers)
                    if (proj.Users.Any(u => u.Id == dev.Id))
                        projectDevs.Add(dev);

                //check if deadline change
                if (original.Deadline != proj.Deadline)
                {
                    if (manager.Id != userId)
                        projectDevs.Add(manager);
                    var msgList = proj.CreateProjectDeadlineChangedMessage(projectDevs);
                    var msgListBody = msgList.First().Body;
                    foreach (var message in msgList)
                        es.Send(message);

                    var notif = proj.Id.CreateProjectNotification(types[10], new List<ApplicationUser>(projectDevs), msgListBody);
                    db.Notifications.Add(notif);
                }

                //check if new Project Manager
                if (original.ProjectManagerId != proj.ProjectManagerId)
                {
                    proj.Users.Remove(origManager);
                    proj.Users.Add(manager);

                    //create emails
                    var msgList = proj.CreateNewProjectManagerMessage(projectDevs);
                    var msg = proj.CreateAssignedToProjectMessage(manager);

BugTracker/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using BugTracker.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BugSleuth - by Abigail West</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Fontdiner+Swanky' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/dt/dt-1.10.11,b-1.1.2,b-colvis-1.1.2,r-2.0.2/datatables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.0.2/css/responsive.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.min.css">
    <link href="~/Content/Site.css" rel="stylesheet" />

</head>
<body>
    <div class="container-fluid">
        <!-- logo-->
        <div class="logo-brand header sidebar rows">
            <div class="logo">
                <h1><a href=@Url.Action("Index", "Home") class="text-title">BugSleuth</a></h1>
            </div>
        </div>
        <!-- BEGIN SIDEBAR -->
        <div class="left side-menu">
            <div class="body rows scroll-y">
                <!-- Scrolling sidebar -->
                <div class="sidebar-inner slimscroller">
                    <!-- User Session -->
                    <div class="media">
                        @{
                            var manager = new UserManager<ApplicationUser>(new Microsoft.AspNet.Identity.EntityFramework.UserStore<ApplicationUser>(new ApplicationDbContext()));
                            var currentUser = manager.FindById(User.Identity.GetUserId());
                        }
                        <div class="media-body">
                            Welcome back,
                            <h4 class="media-heading"><strong>@currentUser.FirstName</strong></h4>
                        </div><!-- End div .media-body -->
                    </div><!-- End div .media -->
                    <!-- Sidebar menu -->
                    <div id="sidebar-menu">
                        <ul>
                            @if (User.IsInRole("Developer") || User.IsInRole("Project Manager") || User.IsInRole("Administrator"))
                            {
                                <li><a href=@Url.Action("Dashboard", "Home")><i class="fa fa-fw fa-bar-chart"></i> Dashboard</a></li>
                                <li><a href=@Url.Action("Index", "Projects")><i class="fa fa-fw fa-puzzle-piece"></i> Projects</a></li>
                                if (User.IsInRole("Administrator"))
                                { <li><a href=@Url.Action("Index", "Tickets")><i class="fa fa-fw fa-ticket"></i> Tickets</a></li> }
                                else
                                {  <li><a href=@Url.Action("UserTickets", "Tickets")><i class="fa fa-fw fa-ticket"></i> Tickets</a></li>}
                                if (User.IsInRole("Project Manager") && !User.IsInRole("Developer") && !User.IsInRole("Administrator"))
                                { <li><a href=@Url.Action("Users", "Admin")><i class="fa fa-fw fa-users"></i> Users </a></li> }
                            }
                                @if (User.IsInRole("Administrator"))
                                {
                                            @*<li><a href=@Url.Action("Roles", "Admin")><i class="fa fa-fw fa-angle-right"></i> Roles</a></li>*@
                                            <li><a href=@Url.Action("Users", "Admin")><i class="fa fa-fw fa-users"></i> Users </a></li>
                                            <li><a href=@Url.Action("Notifications", "Admin")><i class="fa fa-fw fa-paper-plane"></i> Notifications</a></li>
                                }
                            <li><a href=@Url.Action("Index", "Manage")><i class="fa fa-fw fa-user"></i> Profile</a></li>
                        </ul>
                        <div class="clear"></div>
                    </div><!-- End div #sidebar-menu -->
                </div><!-- End div .sidebar-inner .slimscroller -->
            </div><!-- End div .body .rows .scroll-y -->
        </div><!-- End div .footer .rows -->
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
        <div class="right content-page">
            <!-- BEGIN CONTENT HEADER -->
            <div class="header content rows-content-header">
                <!-- Button mobile view to collapse sidebar menu -->
                <button class="button-menu-mobile show-sidebar"><i class="fa fa-bars"></i></button>
                <!-- BEGIN NAVBAR CONTENT-->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container-fluid">
                        <!-- Navbar Header -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <i class="fa fa-angle-double-down"></i>
                            </button>
                        </div>
                        <!-- /navbar header -->
                        <!-- Navbar Collapse -->
                        <div class="navbar-collapse collapse">
                            <!-- left navbar -->
                            <ul class="nav navbar-nav top nav-pad">
                                <li><a href="http://awest.azurewebsites.net" target="_blank" class="logo-pad text-title-sm">abigail west</a></li>
                            </ul>
                            <!-- right navbar -->
                            <ul class="nav navbar-nav navbar-right top-navbar nav-pad">
                                @*<li>@Html.Partial("_RolesPartial")</li>*@
                                <li>@Html.Partial("_LoginPartial")</li>
                                <li><a href="https://awest-bugtracker.azurewebsites.net#about">About</a></li>
                                <li><a href="https://awest-bugtracker.azurewebsites.net#contact">Contact</a></li>
                                <li><a href="https://github.com/abigailwest/BugTracker" target="_blank"><i class="accent fa fa-github fa-2x"></i></a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /div .container-->
                </div>
                <!-- END NAVBAR CONTENT-->
            </div>
            <!-- END CONTENT HEADER -->



            <div class="body content rows scroll-y">
                @RenderBody()
            </div>
            <hr />
            <footer>
                <p>&copy; 2016 - Abigail West</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="https://cdn.datatables.net/t/dt/dt-1.10.11,b-1.1.2,b-colvis-1.1.2,r-2.0.2/datatables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.0.2/js/dataTables.responsive.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="~/Scripts/morris.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.min.js"></script>
    <script src="~/Site Template/js/lanceng.js"></script>
    <script src="~/Scripts/Site.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

BugTracker/Views/Shared/_RolesPartial.cshtml
@using Microsoft.AspNet.Identity
@using BugTracker.HelperExtensions

@{ var userId = User.Identity.GetUserId();
    var roles = userId.ListUserRoles();}
<ul class="nav navbar-nav navbar-right">
    <li>
        @foreach (var role in roles)
        {
        <span style="color:#fff">@role</span>
        }
    </li>
</ul>