BugTracker/Models/CodeFirst/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BugTracker.Models
{
    public class Ticket
    {
        public Ticket()
        {
            this.Logs = new HashSet<Log>();
            this.Comments = new HashSet<Comment>();
            this.Attachments = new HashSet<Attachment>();
        }

        public int Id { get; set; }
        public int? ProjectId { get; set; }
        public string SubmitterId { get; set; }
        public string AssignedToId { get; set; }
        public int? PriorityId { get; set; }
        public int? StatusId { get; set; }
        public int? PhaseId { get; set; }
        public int ActionId { get; set; }
        [Required]
        [StringLength(40, ErrorMessage = "Ticket name must be between {2} and {1} characters.", MinimumLength = 5)]
        public string Name { get; set; }
        public DateTimeOffset Submitted { get; set; }
        public DateTimeOffset LastModified { get; set; }
        public DateTimeOffset Closed { get; set; }
        [Required]
        public string Description { get; set; }

        public virtual Project Project { get; set; }
        public virtual ApplicationUser Submitter { get; set; }
        public virtual ApplicationUser AssignedTo { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual TicketPhase Phase { get; set; }
        public virtual TicketAction Action { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
    }
}

BugTracker/Models/CodeFirst/TicketAction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BugTracker.Models
{
    public class TicketAction
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

BugTracker/Models/CodeFirst/TicketType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BugTracker.Models
{
    public class TicketType
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

BugTracker/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTracker.Models;
using Microsoft.AspNet.Identity;

namespace BugTracker.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        //public ActionResult Index()
        //{
        //    var comments = db.Comments.Include(c => c.Submitter).Include(c => c.Ticket);
        //    return View(comments.ToList());
        //}

        // GET: Comments/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Comment comment = db.Comments.Find(id);
        //    if (comment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(comment);
        //}

        // GET: Comments/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TicketId,SubmitterId,Title,Body,Submitted")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.Submitted = DateTimeOffset.Now;
                comment.SubmitterId = User.Identity.GetUserId();

                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Details", "Tickets", new { id = comment.TicketId });
            }
            return RedirectToAction("Details", "Tickets", new { id = comment.TicketId });
        }

        // GET: Comments/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Comment comment = db.Comments.Find(id);
        //    if (comment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.SubmitterId = new SelectList(db.ApplicationUsers, "Id", "FirstName", comment.SubmitterId);
        //    ViewBag.TicketId = new SelectList(db.Tickets, "Id", "SubmitterId", comment.TicketId);
        //    return View(comment);
        //}

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,TicketId,SubmitterId,Title,Body,Submitted")] Comment comment)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(comment).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.SubmitterId = new SelectList(db.ApplicationUsers, "Id", "FirstName", comment.SubmitterId);
        //    ViewBag.TicketId = new SelectList(db.Tickets, "Id", "SubmitterId", comment.TicketId);
        //    return View(comment);
        //}

        // GET: Comments/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Comment comment = db.Comments.Find(id);
        //    if (comment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(comment);
        //}

        // POST: Comments/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugTracker/Controllers/ProjectsController.cs
using BugTracker.HelperExtensions;
using BugTracker.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    [RequireHttps]
    [Authorize]
    public class ProjectsController : Controller
    {
        private static ApplicationDbContext db = new ApplicationDbContext();
        private Dictionary<int, NotificationType> types = new Dictionary<int, NotificationType>()
        {
            { 1, new NotificationType {Id=9, Name="Ticket Submitted" } },
            { 2, new NotificationType {Id=1, Name="Ticket Assigned" } },
            { 3, new NotificationType {Id=4, Name="Ticket Modified" } },
            { 4, new NotificationType {Id=5, Name="Ticket Reassigned" } },
            { 5, new NotificationType {Id=2, Name="Ticket Resolved" } },
            { 6, new NotificationType {Id=3, Name="Reminder:Update Tickets" } },
            { 7, new NotificationType {Id=6, Name="Project Assigned" } },
            { 8, new NotificationType {Id=7, Name="Project Reassigned" } },
            { 9, new NotificationType {Id=8, Name="New Project Manager" } },
            {10, new NotificationType {Id=9, Name="Project Deadline Changed" } }
        };

        // GET: Projects/Index
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            List<Project> projects;

            if (User.IsInRole("Administrator"))
                projects = db.Projects.Where(p => p.IsResolved != true).OrderByDescending(p => p.Deadline).ToList();
            else
                projects = userId.ListUserProjects().ToList();

            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(projects);
        }

        // GET: Projects/Details/5
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Details(int? id)
        {
            Project project = db.Projects.Include(p=>p.Tickets).FirstOrDefault(p=>p.Id==id);

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (project == null)
                return HttpNotFound();

            return View(project);
        }

        //GET: Projects/Create
        public ActionResult Create()
        {
            var managers = db.Roles.FirstOrDefault(r => r.Name == "Project Manager").Name.UsersInRole().AsEnumerable();
            var developers = db.Roles.FirstOrDefault(r => r.Name == "Developer").Name.UsersInRole().AsEnumerable();
            var submitters = db.Roles.FirstOrDefault(r => r.Name == "Submitter").Name.UsersInRole().AsEnumerable();

            var model = new CreateEditProjectViewModel()
            {
                Project = new Project(),
                ProjectManagers = new SelectList(managers, "Id", "FullName"),
                Developers = new MultiSelectList(developers, "FullName", "FullName"),
                Submitters = new MultiSelectList(submitters, "FullName", "FullName")
            };

            return View(model);
        }

        // POST: Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create(Project project, List<string> SelectedDevelopers, List<string> SelectedSubmitters)
        {
            var userId = User.Identity.GetUserId();
            var manager = db.Users.Find(project.ProjectManagerId);
            var defaultManager = db.Users.Find(userId);

            if (ModelState.IsValid)
            {
                project.Created = DateTimeOffset.Now;
                db.Projects.Add(project);

                if (manager == null && userId.UserIsInRole("Project Manager"))
                {
                    project.ProjectManagerId = userId;
                    project.Users.Add(defaultManager);
                }
                else if (manager != null)
                    project.Users.Add(manager);

                //notify project manager
                var es = new EmailService();
                var msg = project.CreateAssignedToProjectMessage(manager != null ? manager : defaultManager);
                es.Send(msg);

                //log notification
                var notif = project.Id.CreateProjectNotification(types[7], new List<ApplicationUser> { manager != null ? manager : defaultManager }, msg.Body);
                db.Notifications.Add(notif);

                //add users
                if (project.Users != null)
                {
                    foreach (var user in db.Users)
                    {
                        if (SelectedDevelopers.Contains(user.FullName))
                            project.Users.Add(user);
                        if (SelectedSubmitters.Contains(user.FullName) && !project.Users.Any(u => u.FullName == user.FullName))
                            project.Users.Add(user);
                    }
                }

                db.SaveChanges();

                TempData["SuccessMessage"] = "Project " + project.Name + " created.";
                return RedirectToAction("Index");
            }

            TempData["ErrorMessage"] = "Something went wrong. Please try again or submit a ticket.";
            return RedirectToAction("Index");
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Edit(int id)
        {
            Project project = db.Projects.Find(id);

            var projectUsers = project.Users.ToList();
            var managers = db.Roles.FirstOrDefault(r => r.Name == "Project Manager").Name.UsersInRole();
            var developers = db.Roles.FirstOrDefault(r => r.Name == "Developer").Name.UsersInRole();
            var submitters = db.Roles.FirstOrDefault(r => r.Name == "Submitter").Name.UsersInRole();
            var selectedManager = db.Users.Find(project.ProjectManagerId);
            var selectedDevelopers = new List<string>();
            var selectedSubmitters = new List<string>();

            foreach (var user in projectUsers)
            {
                if (user.Id.UserIsInRole("Developer"))
                    selectedDevelopers.Add(user.FullName);
                if (user.Id.UserIsInRole("Submitter"))
                    selectedSubmitters.Add(user.FullName);
            }

            var model = new CreateEditProjectViewModel()
            {
                Project = project,
                ProjectManagers = new SelectList(managers, "Id", "FullName", selectedManager),
                Developers = new MultiSelectList(developers, "FullName", "FullName", selectedDevelopers),
                Submitters = new MultiSelectList(submitters, "FullName", "FullName", selectedSubmitters)
            };

            return View(model);
        }

        // POST: Projects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Edit([Bind(Include = "Id,ProjectManagerId,Name,Deadline,Description,Version")]Project project, List<string> SelectedDevelopers, List<string> SelectedSubmitters)
        {
            var original = db.Projects.AsNoTracking().FirstOrDefault(p => p.Id == project.Id);
            var origManager = db.Users.Find(original.ProjectManagerId);
            var manager = db.Users.Find(project.ProjectManagerId);
            var userId = User.Identity.GetUserId();
            var es = new EmailService();

            var proj = db.Projects.Find(project.Id);
            proj.Name = project.Name;
            proj.ProjectManagerId = project.ProjectManagerId;
            proj.Version = project.Version;
            proj.Deadline = project.Deadline;
            proj.Description = project.Description;
            proj.LastModified = DateTimeOffset.Now;

            if (ModelState.IsValid)
            {
                //reassign current users
                proj.Users.Clear();
                foreach (var user in db.Users)
                {
                    if (SelectedDevelopers.Contains(user.FullName))
                        proj.Users.Add(user);
                    if (SelectedSubmitters.Contains(user.FullName) && !proj.Users.Any(u => u.FullName == user.FullName))
                        proj.Users.Add(user);
                }

                var developers = "Developer".UsersInRole();
                var projectDevs = new List<ApplicationUser>();
                foreach (var dev in developers)
                    if (proj.Users.Any(u => u.Id == dev.Id))
                        projectDevs.Add(dev);

                //check if deadline change
                if (original.Deadline != proj.Deadline)
                {
                    if (manager.Id != userId)
                        projectDevs.Add(manager);
                    var msgList = proj.CreateProjectDeadlineChangedMessage(projectDevs);
                    var msgListBody = msgList.First().Body;
                    foreach (var message in msgList)
                        es.Send(message);

                    var notif = proj.Id.CreateProjectNotification(types[10], new List<ApplicationUser>(projectDevs), msgListBody);
                    db.Notifications.Add(notif);
                }

                //check if new Project Manager
                if (original.ProjectManagerId != proj.ProjectManagerId)
                {
                    proj.Users.Remove(origManager);
                    proj.Users.Add(manager);

                    //create emails
                    var msgList = proj.CreateNewProjectManagerMessage(projectDevs);
                    var msg = proj.CreateAssignedToProjectMessage(manager);

BugTracker/Views/Tickets/Create.cshtml
@model BugTracker.Models.CreateEditTicketViewModel

@{
    ViewBag.Title = "Create";
}

<div class="col-md-8 col-md-offset-2">
    <div class="box-info shadow">
        <h2><strong>Create Ticket</strong> for @Model.ProjectName</h2>
        <div class="box-content">
            @using (Html.BeginForm("Create", "Tickets"))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(m=>m.ProjectId)

                <div class="form-group">
                    @Html.LabelFor(m => m.Ticket.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Ticket.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ticket.Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Ticket.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Ticket.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ticket.Description, "", new { @class = "text-anger" })
                </div>

                if (User.IsInRole("Administrator") || User.IsInRole("Project Manager"))
                {
                    <div class="form-group">
                        <label>Priority</label>
                        @Html.DropDownListFor(m => m.Ticket.PriorityId, Model.Priorities, "Select Priority", new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Ticket.PriorityId, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Ticket.AssignedTo, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.Ticket.AssignedToId, Model.Developers, "Select Developer to Assign", new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ticket.AssignedToId, "", new { @class = "text-danger" })
                    </div>
                }

                <div class="form-group">
                    <label>Development Phase</label>
                    @Html.DropDownListFor(model => model.Ticket.PhaseId, Model.Phases, "Select Development Phase", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ticket.PhaseId, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label>Type</label>
                    @Html.DropDownListFor(model => model.Ticket.ActionId, Model.Actions, "Select Type of Required Work", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ticket.ActionId, "", new { @class = "text-danger" })
                </div>
                <div class="pull-right">
                    <input type="submit" class="btn btn-warning" value="Create Ticket" />
                    <button type="button" class="cancel btn btn-warning">Cancel</button>
                    @*<a href=@Url.Action("Index", "Projects") class="btn btn-warning">To Projects</a>
                    <a href=@Url.Action("UserTickets") class="btn btn-warning">To My Tickets</a>
                    @if (User.IsInRole("Administrator"))
                {
                        <a href=@Url.Action("Index") class="btn btn-warning">To All Tickets</a>
                    }*@
                </div>
            }

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BugTracker/Views/Tickets/Details.cshtml
@model BugTracker.Models.Ticket
@using BugTracker.HelperExtensions
@using Microsoft.AspNet.Identity


<div id="ticketDetails" class="row">
    <h2>
        <span class="pull-right">
            @if (User.IsInRole("Administrator") || User.IsInRole("Project Manager") || User.IsInRole("Developer"))
            { <a href="#changelog" class="section-scroll"><i class="fa fa-angle-down"></i> Change Log</a> }
            <a href="#comments" class="section-scroll"><i class="fa fa-angle-down"></i> Comments</a>
            <a href="#attachments" class="section-scroll"><i class="fa fa-angle-down"></i> Attachments</a>
            <a href=@Url.Action("Create", "Attachments", new { id = Model.Id }) class="btn btn-warning"><i class="fa fa-plus"></i> Attachment</a>
            @if (User.Identity.GetUserId() == Model.AssignedToId)
            {
                <a href=@Url.Action("RequestReassignment", "Tickets", new { id = Model.Id }) class="btn btn-warning">Request Reassignment</a>
            }
        </span>
    </h2>
    <div class="clearfix"></div>
    <br />
    <div class="col-md-12">
        <div class="box-info shadow">
            <h2>Details for <strong>@Model.Name</strong> in @Model.Project.Name</h2>
            <div class="box-content row">
                <div class="col-md-4">
                    <dl class="dl-horizontal">
                        <dt>Project</dt>
                        <dd>@Model.Project.Name</dd>
                        <dt>Deadline</dt>
                        @if (Model.Project.Deadline != null)
                        {
                            <dd>@Model.Project.Deadline.FormatDateTimeOffset()</dd> }
                        else {
                            <dd>none given </dd>}
                        <dt>Assigned To</dt>
                        @if (Model.AssignedTo != null)
                        {
                            <dd>@Model.AssignedTo.FullName</dd> }
                        else {
                            <dd>unassigned</dd> }
                        <dt>Submitted</dt>
                        <dd>@Model.Submitted.FormatDateTimeOffset()</dd>
                    </dl>
                </div>
                <div class="col-md-4">
                    <dl class="dl-horizontal">
                        <dt>Priority</dt>
                        @if (Model.Priority != null)
                        {
                            <dd>@Model.Priority.Name</dd>}
                        else
                        {
                            <dd>none given</dd>}
                        <dt>Description</dt>
                        @if (Model.Description != null)
                        {
                            <dd>@Model.Description</dd> }
                        else {
                            <dd>no description given</dd> }
                    </dl>
                </div>
                <div class="col-md-4">
                    <dl class="dl-horizontal">
                        <dt>Status</dt>
                        @if (Model.Status != null)
                        {
                            <dd>@Model.Status.Name</dd> }
                        else {
                            <dd>unassigned </dd>}
                        <dt>Phase</dt>
                        @if (Model.Phase != null)
                        {
                            <dd>@Model.Phase.Name</dd> }
                        else {
                            <dd>unassigned </dd>}
                        <dt>Type</dt>
                        @if (Model.Action != null)
                        {
                            <dd>@Model.Action.Name</dd> }
                        else {
                            <dd>unassigned </dd>}
                    </dl>
                </div>
                <div class="col-md-12">
                    <div class="pull-right">
                        @if (User.IsInRole("Administrator") || User.IsInRole("Project Manager") || User.IsInRole("Developer"))
                        { <a href=@Url.Action("Edit", "Tickets", new { id = Model.Id }) class="btn btn-warning">Edit</a> }
                        <a href=@Url.Action("UserTickets") class="btn btn-warning">To My Tickets</a>
                        @if (User.IsInRole("Administrator"))
                        {
                            <a href=@Url.Action("Index") class="btn btn-warning">To All Tickets</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div id="comments" class="box-info shadow">
            <h2>Comments</h2>
            <div class="box-content">
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
            {
                    <form action="@Url.Action("Create","Comments")" method="post">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="ticketId" value="@Model.Id" />
                        <input name="Body" class="comment-input" placeholder="Leave a new comment" />
                        <input type="submit" class="comment-submit btn btn-warning" value="Submit">
                    </form>
                }
                <hr />
                @if (Model.Comments.Count == 0)
            {
                    <p>There are no comments for this ticket.</p>
                }
                else
                {
                    <h6>Viewing (@Model.Comments.Count) Comments</h6>
                    foreach (var comment in Model.Comments.OrderBy(c => c.Submitted))
                    {
                        <article class="comment">
                            <div class="row">
                                <p><b>@comment.Submitter.FullName</b> says...</p>
                            </div>
                            <div class="comment-body">
                                <p>@Html.Raw(comment.Body)</p>
                            </div>
                            <div class="comment-meta">
                                @comment.Submitted.DateTime.ToLongDateString() - @comment.Submitted.DateTime.ToShortTimeString()
                            </div>
                        </article>
                    }
                }
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div id="attachments" class="box-info shadow">
            <h2>Attachments</h2>
            <div class="box-content">
                @if (Model.Attachments.Count == 0)
                {
                    if (ViewBag.FileErrorMessage != null)
                    {
                        <p class="text-danger">@ViewBag.FileErrorMessage</p>
                    }
                    <p>There are no attachments for this ticket.</p>
                }
                else
                {
                    if (ViewBag.FileErrorMessage != null)
                    {
                        <p class="text-danger">@ViewBag.FileErrorMessage</p>
                    }
                    <ul class="list-unstyled">
                        @foreach (var attach in Model.Attachments)
                {
                            <li>
                                <i class="fa fa-fw fa-angle-double-right"></i><a href=@Url.Action("Details", "Attachments", new { id = attach.Id })>@attach.Title</a><span class="pull-right">@attach.Submitted.FormatDateTimeOffsetCondensed()</span><div class="clearfix"></div>
                            </li>
                        }
                    </ul>
                }
            </div>
        </div>
    </div>
</div>
@if (User.IsInRole("Administrator") || User.IsInRole("Project Manager") || User.IsInRole("Developer"))
{
    <div class="row">
        <div class="col-md-12">
            <div id="changelog" class="box-info shadow">
                <h2>Change Log</h2>
                <div class="box-content">
                    <table class="data-table-d row-border hover table-striped">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Modified Property</th>
                                <th>New Value</th>
                                <th>Old Value</th>
                                <th>Modified By</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Logs.Count() == 0)
                            {
                                <tr>
                                    <td>There have been no changes to this ticket.</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            }
                            else
                            {
                                foreach (var log in Model.Logs.OrderByDescending(l=>l.Modified))
                                {
                                    <tr>
                                        <td>@log.Modified.FormatDateTimeOffset()</td>
                                        <td><strong>@log.Property</strong></td>
                                        @if (log.NewValue != null)
                                        {
                                            <td>@log.NewValue</td>
                                        }
                                        else
                                        {
                                            <td></td>}
                                        @if (log.OldValue != null)
                                        {
                                            <td>@log.OldValue</td>
                                        }
                                        else
                                        {
                                            <td></td>}

                                        <td>@log.ModifiedBy.FullName</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}