BugTracker/Models/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BugTracker.Models
{
    public class DashboardViewModel
    {
        public IEnumerable<Ticket> Tickets { get; set; }
        public IEnumerable<Attachment> Attachments { get; set; }
        public IEnumerable<Comment> Comments { get; set; }
        public int ProjectsAmt { get; set; }
    }
}

BugTracker/Controllers/AttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTracker.Models;
using System.IO;
using Microsoft.AspNet.Identity;
using BugTracker.HelperExtensions;

namespace BugTracker.Controllers
{
    public class AttachmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Attachments
        //public ActionResult Index()
        //{
        //    var attachments = db.Attachments.Include(a => a.Ticket);
        //    return View(attachments.ToList());
        //}

        // GET: Attachments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = db.Attachments.Find(id);
            if (attachment == null)
            {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // GET: Attachments/Create
        public ActionResult Create(int id)
        {
            var ticket = db.Tickets.Find(id);
            var attachment = new Attachment();
            attachment.Ticket = ticket;
            attachment.TicketId = ticket.Id;

            return View(attachment);
        }

        // POST: Attachments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TicketId,SubmitterId,Title,Description,FilePath,Submitted")] Attachment attachment, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                attachment.Submitted = DateTimeOffset.Now;
                attachment.SubmitterId = User.Identity.GetUserId();

                if (attachment.Title == null)
                {
                    if (attachment.Description != null)
                        attachment.Title = new string(attachment.Description.Take(15).ToArray()) + "...";
                    else
                        attachment.Title = attachment.Submitted.FormatDateTimeOffset();
                }

                if (FileUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Images"), fileName));
                    attachment.FilePath = "~/Images/" + fileName;
                }

                db.Attachments.Add(attachment);
                db.SaveChanges();

                    return RedirectToAction("Details", "Tickets", new { id = attachment.TicketId });
            }
            TempData["FileErrorMessage"] = "File not uploaded. Please try again.";
                return RedirectToAction("Details", "Tickets", new { id = attachment.TicketId });
        }

        // GET: Attachments/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Attachment attachment = db.Attachments.Find(id);
        //    if (attachment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.TicketId = new SelectList(db.Tickets, "Id", "SubmitterId", attachment.TicketId);
        //    return View(attachment);
        //}

        // POST: Attachments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,TicketId,SubmitterId,Title,Description,FilePath,Submitted")] Attachment attachment)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(attachment).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.TicketId = new SelectList(db.Tickets, "Id", "SubmitterId", attachment.TicketId);
        //    return View(attachment);
        //}

        // GET: Attachments/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Attachment attachment = db.Attachments.Find(id);
        //    if (attachment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(attachment);
        //}

        // POST: Attachments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Attachment attachment = db.Attachments.Find(id);
            db.Attachments.Remove(attachment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugTracker/Controllers/ProjectsController.cs
using BugTracker.HelperExtensions;
using BugTracker.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    [RequireHttps]
    [Authorize]
    public class ProjectsController : Controller
    {
        private static ApplicationDbContext db = new ApplicationDbContext();
        private Dictionary<int, NotificationType> types = new Dictionary<int, NotificationType>()
        {
            { 1, new NotificationType {Id=9, Name="Ticket Submitted" } },
            { 2, new NotificationType {Id=1, Name="Ticket Assigned" } },
            { 3, new NotificationType {Id=4, Name="Ticket Modified" } },
            { 4, new NotificationType {Id=5, Name="Ticket Reassigned" } },
            { 5, new NotificationType {Id=2, Name="Ticket Resolved" } },
            { 6, new NotificationType {Id=3, Name="Reminder:Update Tickets" } },
            { 7, new NotificationType {Id=6, Name="Project Assigned" } },
            { 8, new NotificationType {Id=7, Name="Project Reassigned" } },
            { 9, new NotificationType {Id=8, Name="New Project Manager" } },
            {10, new NotificationType {Id=9, Name="Project Deadline Changed" } }
        };

        // GET: Projects/Index
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            List<Project> projects;

            if (User.IsInRole("Administrator"))
                projects = db.Projects.Where(p => p.IsResolved != true).OrderByDescending(p => p.Deadline).ToList();
            else
                projects = userId.ListUserProjects().ToList();

            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(projects);
        }

        // GET: Projects/Details/5
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Details(int? id)
        {
            Project project = db.Projects.Include(p=>p.Tickets).FirstOrDefault(p=>p.Id==id);

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (project == null)
                return HttpNotFound();

            return View(project);
        }

        //GET: Projects/Create
        public ActionResult Create()
        {
            var managers = db.Roles.FirstOrDefault(r => r.Name == "Project Manager").Name.UsersInRole().AsEnumerable();
            var developers = db.Roles.FirstOrDefault(r => r.Name == "Developer").Name.UsersInRole().AsEnumerable();
            var submitters = db.Roles.FirstOrDefault(r => r.Name == "Submitter").Name.UsersInRole().AsEnumerable();

            var model = new CreateEditProjectViewModel()
            {
                Project = new Project(),
                ProjectManagers = new SelectList(managers, "Id", "FullName"),
                Developers = new MultiSelectList(developers, "FullName", "FullName"),
                Submitters = new MultiSelectList(submitters, "FullName", "FullName")
            };

            return View(model);
        }

        // POST: Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create(Project project, List<string> SelectedDevelopers, List<string> SelectedSubmitters)
        {
            var userId = User.Identity.GetUserId();
            var manager = db.Users.Find(project.ProjectManagerId);
            var defaultManager = db.Users.Find(userId);

            if (ModelState.IsValid)
            {
                project.Created = DateTimeOffset.Now;
                db.Projects.Add(project);

                if (manager == null && userId.UserIsInRole("Project Manager"))
                {
                    project.ProjectManagerId = userId;
                    project.Users.Add(defaultManager);
                }
                else if (manager != null)
                    project.Users.Add(manager);

                //notify project manager
                var es = new EmailService();
                var msg = project.CreateAssignedToProjectMessage(manager != null ? manager : defaultManager);
                es.Send(msg);

                //log notification
                var notif = project.Id.CreateProjectNotification(types[7], new List<ApplicationUser> { manager != null ? manager : defaultManager }, msg.Body);
                db.Notifications.Add(notif);

                //add users
                if (project.Users != null)
                {
                    foreach (var user in db.Users)
                    {
                        if (SelectedDevelopers.Contains(user.FullName))
                            project.Users.Add(user);
                        if (SelectedSubmitters.Contains(user.FullName) && !project.Users.Any(u => u.FullName == user.FullName))
                            project.Users.Add(user);
                    }
                }

                db.SaveChanges();

                TempData["SuccessMessage"] = "Project " + project.Name + " created.";
                return RedirectToAction("Index");
            }

            TempData["ErrorMessage"] = "Something went wrong. Please try again or submit a ticket.";
            return RedirectToAction("Index");
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Edit(int id)
        {
            Project project = db.Projects.Find(id);

            var projectUsers = project.Users.ToList();
            var managers = db.Roles.FirstOrDefault(r => r.Name == "Project Manager").Name.UsersInRole();
            var developers = db.Roles.FirstOrDefault(r => r.Name == "Developer").Name.UsersInRole();
            var submitters = db.Roles.FirstOrDefault(r => r.Name == "Submitter").Name.UsersInRole();
            var selectedManager = db.Users.Find(project.ProjectManagerId);
            var selectedDevelopers = new List<string>();
            var selectedSubmitters = new List<string>();

            foreach (var user in projectUsers)
            {
                if (user.Id.UserIsInRole("Developer"))
                    selectedDevelopers.Add(user.FullName);
                if (user.Id.UserIsInRole("Submitter"))
                    selectedSubmitters.Add(user.FullName);
            }

            var model = new CreateEditProjectViewModel()
            {
                Project = project,
                ProjectManagers = new SelectList(managers, "Id", "FullName", selectedManager),
                Developers = new MultiSelectList(developers, "FullName", "FullName", selectedDevelopers),
                Submitters = new MultiSelectList(submitters, "FullName", "FullName", selectedSubmitters)
            };

            return View(model);
        }

        // POST: Projects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Edit([Bind(Include = "Id,ProjectManagerId,Name,Deadline,Description,Version")]Project project, List<string> SelectedDevelopers, List<string> SelectedSubmitters)
        {
            var original = db.Projects.AsNoTracking().FirstOrDefault(p => p.Id == project.Id);
            var origManager = db.Users.Find(original.ProjectManagerId);
            var manager = db.Users.Find(project.ProjectManagerId);
            var userId = User.Identity.GetUserId();
            var es = new EmailService();

            var proj = db.Projects.Find(project.Id);
            proj.Name = project.Name;
            proj.ProjectManagerId = project.ProjectManagerId;
            proj.Version = project.Version;
            proj.Deadline = project.Deadline;
            proj.Description = project.Description;
            proj.LastModified = DateTimeOffset.Now;

            if (ModelState.IsValid)
            {
                //reassign current users
                proj.Users.Clear();
                foreach (var user in db.Users)
                {
                    if (SelectedDevelopers.Contains(user.FullName))
                        proj.Users.Add(user);
                    if (SelectedSubmitters.Contains(user.FullName) && !proj.Users.Any(u => u.FullName == user.FullName))
                        proj.Users.Add(user);
                }

                var developers = "Developer".UsersInRole();
                var projectDevs = new List<ApplicationUser>();
                foreach (var dev in developers)
                    if (proj.Users.Any(u => u.Id == dev.Id))
                        projectDevs.Add(dev);

                //check if deadline change
                if (original.Deadline != proj.Deadline)
                {
                    if (manager.Id != userId)
                        projectDevs.Add(manager);
                    var msgList = proj.CreateProjectDeadlineChangedMessage(projectDevs);
                    var msgListBody = msgList.First().Body;
                    foreach (var message in msgList)
                        es.Send(message);

                    var notif = proj.Id.CreateProjectNotification(types[10], new List<ApplicationUser>(projectDevs), msgListBody);
                    db.Notifications.Add(notif);
                }

                //check if new Project Manager
                if (original.ProjectManagerId != proj.ProjectManagerId)
                {
                    proj.Users.Remove(origManager);
                    proj.Users.Add(manager);

                    //create emails
                    var msgList = proj.CreateNewProjectManagerMessage(projectDevs);
                    var msg = proj.CreateAssignedToProjectMessage(manager);

BugTracker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BugTracker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BugTracker/Views/Home/Dashboard.cshtml
@model BugTracker.Models.DashboardViewModel
@using BugTracker.HelperExtensions
@{
    ViewBag.Title = "Dashboard";
}

<h2>Excuse our mess - this project is still in progress.</h2>
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <!-- projects-->
            <div class="col-md-6">
                <div class="box-info warning">
                    <div class="icon-box">
                        <span class="fa-stack">
                            <i class="fa fa-circle fa-stack-2x text-white"></i>
                            <i class="fa fa-puzzle-piece fa-stack-1x warning"></i>
                        </span>
                    </div>
                    <a href=@Url.Action("Index", "Projects")>
                        <div class="text-box">
                            <h3>@Model.ProjectsAmt</h3>
                            <p>Current Projects</p>
                        </div>
                    </a>
                    <div class="clear"></div>
                </div>
            </div>
            <!-- tickets -->
            <div class="col-md-6">
                <div class="box-info warning">
                    <div class="icon-box">
                        <span class="fa-stack">
                            <i class="fa fa-circle fa-stack-2x text-white"></i>
                            <i class="fa fa-ticket fa-stack-1x warning"></i>
                        </span>
                    </div>
                    @if (User.IsInRole("Administrator"))
                    {
                        @:<a href=@Url.Action("Index", "Tickets")>
                    }
                    else
                    {
                        @:<a href=@Url.Action("UserTickets", "Tickets")>
                    }
                    <div class="text-box">
                        <h3>@Model.Tickets.Count()</h3>
                        <p>Current Tickets</p>
                    </div>
                </a>
                <div class="clear"></div>
        </div>
    </div>
</div>
<div class="box-info shadow">
    <div class="row">
        <!-- priority donut -->
        <div class="col-md-4">
            <h2>Tickets By Priority</h2>
            <div id="ticketsByPriority" class="box-content">
                <div id="priorityDonut" style="height: 125px;" class="col-md-12">
                </div>
                </div>
        </div>
        <!--action donut-->
        <div class="col-md-4">
            <h2>Tickets By Type</h2>
            <div id="ticketByAction" class="box-content">
                <div id="actionDonut" style="height: 125px;" class="col-md-12">
                </div>
                </div>
        </div>
        <!--phase donut-->
        <div class="col-md-4">
            <h2>Tickets By Phase</h2>
            <div id="ticketsByPhase" class="box-content">
                <div id="phaseDonut" style="height: 125px;" class="col-md-12">
                </div>
                </div>
        </div>
    </div>
</div>
@if (User.IsInRole("Administrator"))
{
        <!--UNASSIGNED TICKETS-->
    <div class="row">
        <div class="col-md-12">
            <div id="unassigned" class="box-info shadow">
                <h2><strong>Unassigned</strong> Tickets</h2>
                <div class="box-content">
                    <table id="unassignedTickets" class="data-table-xl hover row-border table-striped compact">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Project</th>
                                <th>Submitted By</th>
                                <th>On</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var ticket in Model.Tickets.Where(t => t.Status.Name != "Resolved" && (t.Priority == null || t.AssignedToId == null)))
                            {
                                <tr>
                                    <td>@ticket.Name</td>
                                    @if (ticket.Project == null)
                                    {
                                        <td>unassigned</td>}
                                    else
                                    {
                                        <td>@ticket.Project.Name</td> }
                                    <td>@ticket.Submitter.FullName</td>
                                    <td>@ticket.Submitted.FormatDateTimeOffsetCondensed()</td>
                                    <td>
                                        <a href=@Url.Action("Details", "Tickets", new { id = ticket.Id }) class="btn btn-xs btn-warning"><i class="fa fa-eye"></i></a>
                                        <a href=@Url.Action("Edit", "Tickets", new { id = ticket.Id }) class="btn btn-xs btn-warning"><i class="fa fa-edit"></i></a>
                                        <a href=@Url.Action("Create", "Attachments", new { id = ticket.Id }) class="btn btn-xs btn-warning"><i class="fa fa-flip-horizontal fa-paperclip"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}
</div>
<!-- counts -->
<div class="col-md-4">
    <!-- comments -->
    <div id="comments" class="box-info">
        <h2>Recent Comments</h2>
        <div class="box-content">
            @foreach (var comment in Model.Comments)
            {
                <h6><b>Ticket: @comment.Ticket.Name</b></h6>
                    <p class="single-line">@comment.Body</p>@*<span class="ellipsis">...</span>*@
                    <p>@comment.Submitted.FormatDateTimeOffset()</p>
                    <br />
            }
        </div>
    </div>
    <!--attachments-->
    <div id="attachments" class="box-info">
        <h2>Recent Attachments</h2>
        <div class="box-content">
            @foreach (var attach in Model.Attachments)
            {
                <h6><b>Ticket: @attach.Ticket.Name</b></h6>
                    <p>@attach.Title</p>
            }
        </div>
    </div>
    @if (User.IsInRole("Administrator"))
    {
        <div id="resolved" class="box-info">
            <h2>Recently Resolved</h2>
            <div class="box-content">
                <dl>
                    @foreach (var resolved in Model.Tickets.Where(t => t.Status.Name == "Resolved"))
                    {
                        <dt>@resolved.Project.Name</dt>
                        <dd>
                            @resolved.Name
                            <a href=@Url.Action("Details", "Tickets", new { id = resolved.Id }) class="pull-right btn btn-warning btn-xs"><i class="fa fa-eye"></i></a>
                        </dd>
                    }
                </dl>
            </div>
        </div>
    }
</div>
</div>
@section Scripts {
<script type="text/javascript">

    $.post('@Url.Action("GetCharts", "Home")').then(function (response) {
        new Morris.Donut({
            element: 'priorityDonut',
            data: response.priorityDonut,
            colors: ['#d48311', '#ed9c28', '#f0a742', '#f4bd71', '#f7d3a1', '#fbe9d0', '#ffffff'],
            resize: true,
        })
        new Morris.Donut({
            element: 'actionDonut',
            data: response.actionDonut,
            colors: ['#d48311', '#ed9c28', '#f0a742', '#f4bd71', '#f7d3a1', '#fbe9d0', '#ffffff'],
            resize: true,
        })
        new Morris.Donut({
            element: 'phaseDonut',
            data: response.phaseDonut,
            colors: ['#d48311', '#ed9c28', '#f0a742', '#f4bd71', '#f7d3a1', '#fbe9d0', '#ffffff'],
            resize: true,
        })
    });
</script>}

BugTracker/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_AnonLayout.cshtml";
}

<div class="row">
    <div class="col-md-3 full-content-xsmall animated fadeInDownBig">
        <div class="login-wrap">
            <a class="section-scroll btn btn-warning text-white btn-block btn-lg" href="#about">Learn More</a>
        </div>
    </div>
    <div class="col-md-3 col-md-offset-6 full-content-xsmall animated fadeInDownBig">
        <div class="login-wrap">
            <a href=@Url.Action("Login", "Account") class="btn btn-warning text-white btn-block"><i class="fa fa-unlock"></i> Login</a>
            <a href=@Url.Action("Register", "Account") class="btn btn-warning text-white btn-block"><i class="fa fa-rocket fa-inverse"></i> Register</a>
        </div>
        <div class="login-wrap">
            <h4>Demo application as:</h4>
            @using (Html.BeginForm("LoginGuestSubmitter", "Account"))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-dark btn-block">Submitter</button>
            }
            @using (Html.BeginForm("LoginGuestDeveloper", "Account"))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-dark btn-block">Developer</button>
            }
            @using (Html.BeginForm("LoginGuestProjectManager", "Account"))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-dark btn-block">Project Manager</button>
            }
            @using (Html.BeginForm("LoginGuestAdministrator", "Account"))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-dark btn-block">Administrator</button>
            }
        </div>
    </div>
    </div>

<div class="row">
    <div id="title" class="col-md-5">
        <h4 style="color:#f0ad4e">Welcome to</h4>
        <h1 class="accent app-title text-right">Bug Sleuth</h1>
    </div>
</div>